In [5]:
import pandas as pd
import numpy as np

In [6]:
import matplotlib.pyplot as plt
import seaborn as sns

# USING machine learning model -- XGBOOST

In [7]:
!pip install tensorflow
!pip install scikit-learn

Requirement already satisfied: tensorflow in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (2.20.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.3.1)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (24.2)
Requirement already satisfied: protobuf>=5.28.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (5.29.5)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.2.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (4.14.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.0.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (1.73.1)
Requirement already satisfied: tensorboard~=2.20.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.12.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.2.0)
Requirement already satisfied: h5py>=3.11.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (0.5.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.6.15)
Requirement already satisfied: markdown>=2.6.8 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (3.10)
Requirement already satisfied: pillow in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (11.2.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (3.0.6)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras>=3.10.0->tensorflow) (14.0.0)
Requirement already satisfied: namex in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras>=3.10.0->tensorflow) (0.17.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from rich->keras>=3.10.0->tensorflow) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from rich->keras>=3.10.0->tensorflow) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.2)

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: scikit-learn in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (1.7.0)
Requirement already satisfied: numpy>=1.22.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.2.0)
Requirement already satisfied: scipy>=1.8.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
from tensorflow import keras

In [9]:
df= pd.read_csv(r"C:\Downloads\Churn_Modelling.csv")

In [10]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [11]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [14]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [15]:
df=df.drop(columns=['RowNumber','CustomerId',],axis=1)

In [16]:
df=df.drop(columns=['Surname',],axis=1)

In [17]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

# label encoding

In [18]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [19]:
df['Gender'] = label_encoder.fit_transform(df['Gender']) 
# female=0 , male=1

In [20]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [21]:
df['Geography'] = label_encoder.fit_transform(df['Geography']) 
# france=0, spain=2, genmany=1

In [22]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,0,0,42,2,0.00,1,1,1,101348.88,1
1,608,2,0,41,1,83807.86,1,0,1,112542.58,0
2,502,0,0,42,8,159660.80,3,1,0,113931.57,1
3,699,0,0,39,1,0.00,2,0,0,93826.63,0
4,850,2,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,0,1,39,5,0.00,2,1,0,96270.64,0
9996,516,0,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,0,0,36,7,0.00,1,0,1,42085.58,1
9998,772,1,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,0,0,28,4,130142.79,1,1,0,38190.78,0

In [23]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [24]:
df.corr()['Exited']

CreditScore       -0.027094
Geography          0.035943
Gender            -0.106512
Age                0.285323
Tenure            -0.014001
Balance            0.118533
NumOfProducts     -0.047820
HasCrCard         -0.007138
IsActiveMember    -0.156128
EstimatedSalary    0.012097
Exited             1.000000
Name: Exited, dtype: float64

In [42]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,0,0,42,2,0.00,1,1,1,101348.88,1
1,608,2,0,41,1,83807.86,1,0,1,112542.58,0
2,502,0,0,42,8,159660.80,3,1,0,113931.57,1
3,699,0,0,39,1,0.00,2,0,0,93826.63,0
4,850,2,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,0,1,39,5,0.00,2,1,0,96270.64,0
9996,516,0,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,0,0,36,7,0.00,1,0,1,42085.58,1
9998,772,1,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,0,0,28,4,130142.79,1,1,0,38190.78,0

In [43]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

# train test split

In [68]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Scaling

In [69]:
# scalling 
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
x_train_scaled = scaler.fit_transform(X_train)
x_test_scaled= scaler.fit_transform(X_test)

In [70]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (3.1.1)
Requirement already satisfied: numpy in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from xgboost) (2.2.0)
Requirement already satisfied: scipy in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from xgboost) (1.15.3)

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [71]:
from xgboost import XGBClassifier

In [48]:
model1 = XGBClassifier(objective='binary:logistic', 
                      n_estimators=100, 
                      learning_rate=0.1, 
                      max_depth=3, 
                      random_state=42,
                      use_label_encoder=False, 
                      eval_metric='logloss')

In [51]:
model1.fit(x_train_scaled,y_train)

C:\Users\arind\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:199: UserWarning: [15:37:41] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [52]:
y_pred89=model1.predict(x_test_scaled)

In [53]:
from sklearn.metrics import accuracy_score

In [54]:
accuracy=accuracy_score(y_test1,y_pred89)

In [55]:
accuracy

0.773

In [ ]:
# ##############################################

# Using Deep learning model --ANN

In [42]:
from sklearn.metrics import mean_absolute_error,accuracy_score

In [56]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Dropout
from tensorflow.keras.layers import BatchNormalization

In [57]:
model= Sequential()
model.add(Dense(128,activation="relu",input_dim=10))
model.add(BatchNormalization())
# model.add(Dense(80,activation="relu"))
model.add(Dense(80,activation="relu"))
model.add(Dropout(0.2))
model.add(Dense(64,activation="relu"))
model.add(Dense(32,activation="relu"))
model.add(Dropout(0.2))
# model.add(Dense(8,activation="relu"))
model.add(Dense(1,activation="sigmoid"))

# Dropout(0.2)

C:\Users\arind\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [58]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 128)                 │           1,408 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization                  │ (None, 128)                 │             512 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 80)                  │          10,320 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 80)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 64)                  │           5,184 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 32)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 19,537 (76.32 KB)

 Trainable params: 19,281 (75.32 KB)

 Non-trainable params: 256 (1.00 KB)

In [60]:
from tensorflow.keras.optimizers import Adam
optimizer = Adam(learning_rate=1e-3)

In [61]:
model.compile(loss="binary_crossentropy",optimizer=optimizer,metrics=['accuracy'])

In [62]:
from tensorflow.keras.callbacks import EarlyStopping,ReduceLROnPlateau
callbacks = [
    EarlyStopping(monitor='val_accuracy', patience=25, restore_best_weights=True, min_delta=0.005),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=10, min_lr=1e-6, verbose=1)
]

In [63]:
model.fit(x_train_scaled,y_train,epochs=1000, validation_split=0.2, callbacks=callbacks,
    verbose=1)

Epoch 1/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.8047 - loss: 0.4482 - val_accuracy: 0.8413 - val_loss: 0.4380 - learning_rate: 0.0010
Epoch 2/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8427 - loss: 0.3888 - val_accuracy: 0.8506 - val_loss: 0.3685 - learning_rate: 0.0010
Epoch 3/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8489 - loss: 0.3709 - val_accuracy: 0.8531 - val_loss: 0.3548 - learning_rate: 0.0010
Epoch 4/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8531 - loss: 0.3662 - val_accuracy: 0.8500 - val_loss: 0.3515 - learning_rate: 0.0010
Epoch 5/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8555 - loss: 0.3560 - val_accuracy: 0.8512 - val_loss: 0.3501 - learning_rate: 0.0010
Epoch 6/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8531 - loss: 0.3501 - val_accuracy: 0.8519 - val_loss: 0.3402 - learning_rate: 0.0010
Epoch 7/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8553 - loss: 0.3454 - val_accuracy: 0.8531 - val_loss: 0.3478 - learning_rate: 0.0010
Epoch 8/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8591 - loss: 0.3472 - val_accuracy: 0.8481 - val_loss: 0.3499 - learning_rate: 0.0010
Epoch 9/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8594 - loss: 0.3370 - val_accuracy: 0.8550 - val_loss: 0.3444 - learning_rate: 0.0010
Epoch 10/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8633 - loss: 0.3393 - val_accuracy: 0.8562 - val_loss: 0.3450 - learning_rate: 0.0010
Epoch 11/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8636 - loss: 0.3328 - val_accuracy: 0.8562 - val_loss: 0.3450 - learning_rate: 0.0010
Epoch 12/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8633 - loss: 0.3336 - val_accuracy: 0.8519 - val_loss: 0.3488 - learning_rate: 0.0010
Epoch 13/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8655 - loss: 0.3290 - val_accuracy: 0.8550 - val_loss: 0.3474 - learning_rate: 0.0010
Epoch 14/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8659 - loss: 0.3257 - val_accuracy: 0.8556 - val_loss: 0.3488 - learning_rate: 0.0010
Epoch 15/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8684 - loss: 0.3250 - val_accuracy: 0.8556 - val_loss: 0.3469 - learning_rate: 0.0010
Epoch 16/1000
192/200 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8771 - loss: 0.3062
Epoch 16: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8686 - loss: 0.3229 - val_accuracy: 0.8600 - val_loss: 0.3446 - learning_rate: 0.0010
Epoch 17/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8714 - loss: 0.3106 - val_accuracy: 0.8562 - val_loss: 0.3535 - learning_rate: 5.0000e-04
Epoch 18/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8727 - loss: 0.3075 - val_accuracy: 0.8550 - val_loss: 0.3557 - learning_rate: 5.0000e-04
Epoch 19/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8722 - loss: 0.3055 - val_accuracy: 0.8544 - val_loss: 0.3563 - learning_rate: 5.0000e-04
Epoch 20/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8748 - loss: 0.3028 - val_accuracy: 0.8569 - val_loss: 0.3536 - learning_rate: 5.0000e-04
Epoch 21/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8777 - loss: 0.3006 - val_accuracy: 0.8562 - val_loss: 0.3534 - learning_rate: 5.0000e-04
Epoch 22/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8798 - loss: 0.2967 - val_accuracy: 0.8587 - val_loss: 0.3498 - learning_rate: 5.0000e-04
Epoch 23/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8778 - loss: 0.2949 - val_accuracy: 0.8594 - val_loss: 0.3502 - learning_rate: 5.0000e-04
Epoch 24/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8744 - loss: 0.3008 - val_accuracy: 0.8575 - val_loss: 0.3514 - learning_rate: 5.0000e-04
Epoch 25/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8758 - loss: 0.2942 - val_accuracy: 0.8531 - val_loss: 0.3666 - learning_rate: 5.0000e-04
Epoch 26/1000
192/200 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8766 - loss: 0.3004
Epoch 26: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8803 - loss: 0.2940 - val_accuracy: 0.8537 - val_loss: 0.3585 - learning_rate: 5.0000e-04
Epoch 27/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8808 - loss: 0.2829 - val_accuracy: 0.8562 - val_loss: 0.3586 - learning_rate: 2.5000e-04
Epoch 28/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8827 - loss: 0.2780 - val_accuracy: 0.8537 - val_loss: 0.3591 - learning_rate: 2.5000e-04
Epoch 29/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8816 - loss: 0.2787 - val_accuracy: 0.8531 - val_loss: 0.3664 - learning_rate: 2.5000e-04
Epoch 30/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8841 - loss: 0.2790 - val_accuracy: 0.8537 - val_loss: 0.3637 - learning_rate: 2.5000e-04
Epoch 31/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8827 - loss: 0.2796 - val_accuracy: 0.8550 - val_loss: 0.3640 - learning_rate: 2.5000e-04
Epoch 32/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8844 - loss: 0.2753 - val_accuracy: 0.8525 - val_loss: 0.3649 - learning_rate: 2.5000e-04
Epoch 33/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8878 - loss: 0.2686 - val_accuracy: 0.8569 - val_loss: 0.3672 - learning_rate: 2.5000e-04
Epoch 34/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8819 - loss: 0.2752 - val_accuracy: 0.8575 - val_loss: 0.3667 - learning_rate: 2.5000e-04
Epoch 35/1000
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8814 - loss: 0.2733 - val_accuracy: 0.8575 - val_loss: 0.3641 - learning_rate: 2.5000e-04

In [65]:
y_log=model.predict(x_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

# set threshold

In [66]:
y_pred=np.where(y_log >0.5,1,0)

In [67]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8585

# fine tuning using keras tuner

In [202]:
# fine tune keras 
!pip install -U keras-tuner

Requirement already satisfied: keras-tuner in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (1.4.7)
Requirement already satisfied: keras in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras-tuner) (3.12.0)
Requirement already satisfied: packaging in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras-tuner) (24.2)
Requirement already satisfied: requests in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras-tuner) (2.32.4)
Requirement already satisfied: kt-legacy in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras-tuner) (1.0.5)
Requirement already satisfied: absl-py in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras->keras-tuner) (2.3.1)
Requirement already satisfied: numpy in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras->keras-tuner) (2.2.0)
Requirement already satisfied: rich in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras->keras-tuner) (14.0.0)
Requirement already satisfied: namex in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras->keras-tuner) (3.15.1)
Requirement already satisfied: optree in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras->keras-tuner) (0.17.0)
Requirement already satisfied: ml-dtypes in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras->keras-tuner) (0.5.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from optree->keras->keras-tuner) (4.14.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from requests->keras-tuner) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from requests->keras-tuner) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from requests->keras-tuner) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from requests->keras-tuner) (2025.6.15)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from rich->keras->keras-tuner) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from rich->keras->keras-tuner) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [203]:
import kerastuner as kt

C:\Users\arind\AppData\Local\Temp\ipykernel_1956\1654478174.py:1: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt

In [72]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam, RMSprop, SGD
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
import keras_tuner as kt

def build_model2(hp):
    model2 = Sequential()

    # Tune number of hidden layers
    num_layers = hp.Int('num_layers', min_value=1, max_value=6)

    for i in range(num_layers):
        # Number of units per layer
        units = hp.Int('units_' + str(i), min_value=16, max_value=256, step=16)

        # Add dense layer
        if i == 0:
            model2.add(Dense(units, activation='relu', input_dim=10))
        else:
            model2.add(Dense(units, activation='relu'))

        # BatchNorm and Dropout
        model2.add(BatchNormalization())
        model2.add(Dropout(hp.Float('dropout_' + str(i), min_value=0.1, max_value=0.4, step=0.1)))

    # Output layer (Binary classification)
    model2.add(Dense(1, activation='sigmoid'))

    # Tune optimizer and learning rate
    optimizer_choice = hp.Choice('optimizer', ['adam', 'rmsprop', 'sgd'])
    learning_rate = hp.Float('learning_rate', min_value=1e-4, max_value=1e-2, sampling='log')

    if optimizer_choice == 'adam':
        optimizer = Adam(learning_rate=learning_rate)
    elif optimizer_choice == 'rmsprop':
        optimizer = RMSprop(learning_rate=learning_rate)
    else:
        optimizer = SGD(learning_rate=learning_rate, momentum=0.9)

    # Compile model
    model2.compile(
        optimizer=optimizer,
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model2

# --- Tuner ---
tuner = kt.RandomSearch(
    build_model2,
    objective='val_accuracy',
    max_trials=25,
    directory='my_dir',
    project_name='my_project5856'
)

# --- Callbacks ---
callbacks = [
    EarlyStopping(monitor='val_accuracy', patience=30, restore_best_weights=True, min_delta=0.005, verbose=1),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=10, min_lr=1e-6, verbose=1)
]

# --- Search best model ---
tuner.search(
    x_train_scaled, y_train,
    validation_data=(x_test_scaled, y_test),
    epochs=500,
    callbacks=callbacks,
    verbose=1
)

Trial 25 Complete [00h 01m 20s]
val_accuracy: 0.8679999709129333

Best val_accuracy So Far: 0.8684999942779541
Total elapsed time: 02h 48m 59s

In [81]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 3,
 'units_0': 208,
 'dropout_0': 0.30000000000000004,
 'optimizer': 'rmsprop',
 'learning_rate': 0.008135578909273642,
 'units_1': 208,
 'dropout_1': 0.4,
 'units_2': 96,
 'dropout_2': 0.1,
 'units_3': 112,
 'dropout_3': 0.4,
 'units_4': 112,
 'dropout_4': 0.2,
 'units_5': 208,
 'dropout_5': 0.4}

In [82]:
model2= tuner.get_best_models(num_models=1)[0]

C:\Users\arind\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\arind\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\saving\saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 16 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [83]:
model2.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 208)                 │           2,288 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization                  │ (None, 208)                 │             832 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 208)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 208)                 │          43,472 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_1                │ (None, 208)                 │             832 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 208)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 96)                  │          20,064 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_2                │ (None, 96)                  │             384 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 96)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │              97 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 67,969 (265.50 KB)

 Trainable params: 66,945 (261.50 KB)

 Non-trainable params: 1,024 (4.00 KB)

In [84]:
model2.fit(x_train_scaled,y_train,epochs=80,initial_epoch=51,validation_data=(x_test_scaled,y_test),verbose=True,callbacks=callbacks)

Epoch 52/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.8526 - loss: 0.3580 - val_accuracy: 0.8610 - val_loss: 0.3442 - learning_rate: 0.0081
Epoch 53/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8547 - loss: 0.3531 - val_accuracy: 0.8545 - val_loss: 0.3423 - learning_rate: 0.0081
Epoch 54/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8529 - loss: 0.3483 - val_accuracy: 0.8695 - val_loss: 0.3402 - learning_rate: 0.0081
Epoch 55/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8584 - loss: 0.3530 - val_accuracy: 0.8650 - val_loss: 0.3327 - learning_rate: 0.0081
Epoch 56/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8593 - loss: 0.3477 - val_accuracy: 0.8685 - val_loss: 0.3336 - learning_rate: 0.0081
Epoch 57/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8580 - loss: 0.3487 - val_accuracy: 0.8585 - val_loss: 0.3431 - learning_rate: 0.0081
Epoch 58/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8583 - loss: 0.3493 - val_accuracy: 0.8590 - val_loss: 0.3461 - learning_rate: 0.0081
Epoch 59/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8600 - loss: 0.3475 - val_accuracy: 0.8680 - val_loss: 0.3415 - learning_rate: 0.0081
Epoch 60/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8600 - loss: 0.3492 - val_accuracy: 0.8645 - val_loss: 0.3378 - learning_rate: 0.0081
Epoch 61/80
244/250 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8525 - loss: 0.3478
Epoch 61: ReduceLROnPlateau reducing learning rate to 0.004067789297550917.
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8568 - loss: 0.3422 - val_accuracy: 0.8540 - val_loss: 0.3462 - learning_rate: 0.0081
Epoch 62/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8639 - loss: 0.3372 - val_accuracy: 0.8615 - val_loss: 0.3383 - learning_rate: 0.0041
Epoch 63/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8631 - loss: 0.3400 - val_accuracy: 0.8635 - val_loss: 0.3353 - learning_rate: 0.0041
Epoch 64/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8654 - loss: 0.3331 - val_accuracy: 0.8620 - val_loss: 0.3388 - learning_rate: 0.0041
Epoch 65/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8650 - loss: 0.3374 - val_accuracy: 0.8635 - val_loss: 0.3355 - learning_rate: 0.0041
Epoch 66/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8622 - loss: 0.3338 - val_accuracy: 0.8650 - val_loss: 0.3331 - learning_rate: 0.0041
Epoch 67/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8668 - loss: 0.3304 - val_accuracy: 0.8635 - val_loss: 0.3353 - learning_rate: 0.0041
Epoch 68/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8640 - loss: 0.3325 - val_accuracy: 0.8635 - val_loss: 0.3388 - learning_rate: 0.0041
Epoch 69/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8690 - loss: 0.3334 - val_accuracy: 0.8620 - val_loss: 0.3368 - learning_rate: 0.0041
Epoch 70/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8630 - loss: 0.3323 - val_accuracy: 0.8640 - val_loss: 0.3343 - learning_rate: 0.0041
Epoch 71/80
239/250 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8629 - loss: 0.3299
Epoch 71: ReduceLROnPlateau reducing learning rate to 0.0020338946487754583.
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8611 - loss: 0.3349 - val_accuracy: 0.8650 - val_loss: 0.3369 - learning_rate: 0.0041
Epoch 72/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8656 - loss: 0.3286 - val_accuracy: 0.8630 - val_loss: 0.3352 - learning_rate: 0.0020
Epoch 73/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8696 - loss: 0.3228 - val_accuracy: 0.8630 - val_loss: 0.3361 - learning_rate: 0.0020
Epoch 74/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8640 - loss: 0.3276 - val_accuracy: 0.8640 - val_loss: 0.3342 - learning_rate: 0.0020
Epoch 75/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8684 - loss: 0.3248 - val_accuracy: 0.8650 - val_loss: 0.3359 - learning_rate: 0.0020
Epoch 76/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8694 - loss: 0.3291 - val_accuracy: 0.8645 - val_loss: 0.3342 - learning_rate: 0.0020
Epoch 77/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8655 - loss: 0.3279 - val_accuracy: 0.8650 - val_loss: 0.3368 - learning_rate: 0.0020
Epoch 78/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8634 - loss: 0.3279 - val_accuracy: 0.8665 - val_loss: 0.3391 - learning_rate: 0.0020
Epoch 79/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8646 - loss: 0.3242 - val_accuracy: 0.8650 - val_loss: 0.3393 - learning_rate: 0.0020
Epoch 80/80
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8659 - loss: 0.3238 - val_accuracy: 0.8625 - val_loss: 0.3400 - learning_rate: 0.0020
Restoring model weights from the end of the best epoch: 52.

In [87]:
y_log2=model2.predict(x_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

set threshold

In [88]:
y_pred=np.where(y_log2 >0.5,1,0)

In [89]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.861